name: Docker Image CI

on:
  push:
    branches: [ "feature/test" ]
  pull_request:
    branches: [ "feature/test" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile.debug2 --tag bearcatpanda/orchestrator:$(date +%s)
